### PR TITLE
#355: improve flyout

### PR DESCRIPTION
**Pull request by fabianpage**
https://user-images.githubusercontent.com/8473/199265207-0882ce8d-44c1-4c86-8886-18aaaae4271f.mp4

Waiting for the correct chevron icon

### CODE REVIEW

**Comment by pgoellnitz** [comment]
Hi @fabianpage, maybe you have it on your list. But could you add the chevron to the "Zurück" link on the species page and also correct the style of the link (remove the underline).

**Comment by fabianpage** [comment]
zurück link adapted to design
replaced icons

**Comment by pgoellnitz** [comment]
Hi @fabianpage, I just realized that the images in profile have a sizing issue on narrow screens.

image

**Comment by pgoellnitz** [comment]
Also the marker somehow does not size correctly in Chrome.
image


 Firefox looks fine.

**Review by pgoellnitz — APPROVED** [review]
Awesome!

are those png assets used: [ico_arrow_right.png](https://github.com/globe-swiss/phaenonet-client/pull/380/files#diff-2d96dcda5724db9211c9646bf361c3c36be7c8ac4f6308da0b0b3e6b99f902ce), [ico_arrow_left.png](https://github.com/globe-swiss/phaenonet-client/pull/380/files#diff-2d7bfe15a720d30324a5debd8d541eb43f7049e223f7ce3980d50b8e400d2ee2)

**Comment by fabianpage** [comment]
They icons are used for the back and forward links

**Comment by pgoellnitz** [comment]
> They icons are used for the back and forward links

ok, to me it seemed like only the .svg variants are used.

**Pull request merged**
